# Generated by Django 5.2.15 on 2026-06-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('branch_created', 'Branch Created'), ('branch_updated', 'Branch Updated'), ('package_registered', 'Package Registered'), ('package_status_changed', 'Package Status Changed'), ('package_arrival', 'Package Arrival Confirmed'), ('package_delivered', 'Package Delivered'), ('vehicle_assigned', 'Vehicle Assigned')], max_length=50),
        ),
    ]
