# Generated by Django 5.2.15 on 2026-06-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin_manager', 'System Administrator / Manager'), ('branch_officer', 'Branch Officer')], default='admin_manager', max_length=20),
        ),
    ]
