# Generated by Django 5.2.15 on 2026-06-05 08:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccms_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('driver_name', models.CharField(max_length=255)),
                ('driver_phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_transit', 'In Transit'), ('maintenance', 'Under Maintenance'), ('inactive', 'Inactive')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['plate_number'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('sender_full_name', models.CharField(max_length=255)),
                ('sender_id_number', models.CharField(max_length=50)),
                ('sender_phone', models.CharField(max_length=20)),
                ('receiver_full_name', models.CharField(max_length=255)),
                ('receiver_id_number', models.CharField(max_length=50)),
                ('receiver_phone', models.CharField(max_length=20)),
                ('package_type', models.CharField(choices=[('documents', 'Documents'), ('parcel', 'Parcel'), ('cargo', 'Cargo'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transport_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('ready_for_dispatch', 'Ready for Dispatch'), ('in_transit', 'In Transit'), ('arrived', 'Arrived at Destination'), ('ready_for_pickup', 'Ready for Pickup'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='registered', max_length=30)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_receiver_id_number', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_packages', to=settings.AUTH_USER_MODEL)),
                ('destination_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_packages', to='ccms_app.branch')),
                ('origin_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_packages', to='ccms_app.branch')),
                ('received_at_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_packages', to='ccms_app.branch')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_packages', to=settings.AUTH_USER_MODEL)),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_packages', to=settings.AUTH_USER_MODEL)),
                ('assigned_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='ccms_app.vehicle')),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('ready_for_dispatch', 'Ready for Dispatch'), ('in_transit', 'In Transit'), ('arrived', 'Arrived at Destination'), ('ready_for_pickup', 'Ready for Pickup'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=30)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_status_changes', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='ccms_app.package')),
            ],
            options={
                'verbose_name_plural': 'package status histories',
                'ordering': ['-changed_at'],
            },
        ),
    ]
