import io
from datetime import date

from django.http import HttpResponse
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill
from reportlab.lib import colors
from reportlab.lib.pagesizes import landscape, letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


def _filename(slug, fmt, date_from, date_to):
    return f'ccms_{slug}_{date_from}_{date_to}.{fmt}'


def export_excel(report_data):
    wb = Workbook()
    ws = wb.active
    ws.title = 'Report'

    header_font = Font(bold=True, color='FFFFFF')
    header_fill = PatternFill(start_color='1E2A4A', end_color='1E2A4A', fill_type='solid')

    ws.append([report_data['title']])
    ws['A1'].font = Font(bold=True, size=14)
    ws.append([f"Period: {report_data['date_from']} to {report_data['date_to']}"])
    ws.append([])

    ws.append(report_data['headers'])
    header_row = ws.max_row
    for cell in ws[header_row]:
        cell.font = header_font
        cell.fill = header_fill

    for row in report_data['rows']:
        ws.append(row)

    if report_data.get('summary'):
        ws.append([])
        for key, value in report_data['summary'].items():
            ws.append([key, value])

    for col in ws.columns:
        max_len = 0
        col_letter = col[0].column_letter
        for cell in col:
            if cell.value:
                max_len = max(max_len, len(str(cell.value)))
        ws.column_dimensions[col_letter].width = min(max_len + 2, 40)

    buffer = io.BytesIO()
    wb.save(buffer)
    buffer.seek(0)

    response = HttpResponse(
        buffer.getvalue(),
        content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    )
    response['Content-Disposition'] = f'attachment; filename="{_filename(report_data["slug"], "xlsx", report_data["date_from"], report_data["date_to"])}"'
    return response


def export_pdf(report_data):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=landscape(letter), topMargin=0.5 * inch)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle('Title', parent=styles['Heading1'], fontSize=16, spaceAfter=6)
    subtitle_style = ParagraphStyle('Subtitle', parent=styles['Normal'], fontSize=10, textColor=colors.grey)

    elements = [
        Paragraph(report_data['title'], title_style),
        Paragraph(
            f"Period: {report_data['date_from']} to {report_data['date_to']} &nbsp;|&nbsp; Generated by CCMS",
            subtitle_style,
        ),
        Spacer(1, 0.2 * inch),
    ]

    table_data = [report_data['headers']] + [
        [str(cell) for cell in row] for row in report_data['rows']
    ]

    if not report_data['rows']:
        table_data.append(['No data for the selected period.'] + [''] * (len(report_data['headers']) - 1))

    col_count = len(report_data['headers'])
    page_width = landscape(letter)[0] - inch
    col_width = page_width / col_count

    table = Table(table_data, colWidths=[col_width] * col_count, repeatRows=1)
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1E2A4A')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 8),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#F8FAFC')]),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]))
    elements.append(table)

    if report_data.get('summary'):
        elements.append(Spacer(1, 0.2 * inch))
        summary_text = ' &nbsp;|&nbsp; '.join(
            f'<b>{k}:</b> {v}' for k, v in report_data['summary'].items()
        )
        elements.append(Paragraph(summary_text, styles['Normal']))

    doc.build(elements)
    buffer.seek(0)

    response = HttpResponse(buffer.getvalue(), content_type='application/pdf')
    response['Content-Disposition'] = f'attachment; filename="{_filename(report_data["slug"], "pdf", report_data["date_from"], report_data["date_to"])}"'
    return response
